version: '2'
services:

  mongodb2:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  flaskserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    links:
      - mongodb2
    depends_on:
      - mongodb2